## Q12)

In [45]:
import pandas as pd
energy = pd.read_csv('energy.csv',parse_dates=['date'])
energy = energy.drop(['date','lights'],axis=1)
energy.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.8900000000,47.5966666667,19.2000000000,44.7900000000,19.7900000000,44.7300000000,19.0000000000,45.5666666667,17.1666666667,...,17.0333333333,45.5300000000,6.6000000000,733.5000000000,92.0000000000,7.0000000000,63.0000000000,5.3000000000,13.2754331571,13.2754331571
1,60,19.8900000000,46.6933333333,19.2000000000,44.7225000000,19.7900000000,44.7900000000,19.0000000000,45.9925000000,17.1666666667,...,17.0666666667,45.5600000000,6.4833333333,733.6000000000,92.0000000000,6.6666666667,59.1666666667,5.2000000000,18.6061949818,18.6061949818
2,50,19.8900000000,46.3000000000,19.2000000000,44.6266666667,19.7900000000,44.9333333333,18.9266666667,45.8900000000,17.1666666667,...,17.0000000000,45.5000000000,6.3666666667,733.7000000000,92.0000000000,6.3333333333,55.3333333333,5.1000000000,28.6426681676,28.6426681676
3,50,19.8900000000,46.0666666667,19.2000000000,44.5900000000,19.7900000000,45.0000000000,18.8900000000,45.7233333333,17.1666666667,...,17.0000000000,45.4000000000,6.2500000000,733.8000000000,92.0000000000,6.0000000000,51.5000000000,5.0000000000,45.4103894997,45.4103894997
4,60,19.8900000000,46.3333333333,19.2000000000,44.5300000000,19.7900000000,45.0000000000,18.8900000000,45.5300000000,17.2000000000,...,17.0000000000,45.4000000000,6.1333333333,733.9000000000,92.0000000000,5.6666666667,47.6666666667,4.9000000000,10.0840965519,10.0840965519

In [46]:
energy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Appliances   19735 non-null  int64
 1   T1           19735 non-null  float64
 2   RH_1         19735 non-null  float64
 3   T2           19735 non-null  float64
 4   RH_2         19735 non-null  float64
 5   T3           19735 non-null  float64
 6   RH_3         19735 non-null  float64
 7   T4           19735 non-null  float64
 8   RH_4         19735 non-null  float64
 9   T5           19735 non-null  float64
 10  RH_5         19735 non-null  float64
 11  T6           19735 non-null  float64
 12  RH_6         19735 non-null  float64
 13  T7           19735 non-null  float64
 14  RH_7         19735 non-null  float64
 15  T8           19735 non-null  float64
 16  RH_8         19735 non-null  float64
 17  T9           19735 non-null  float64
 18  RH_9         19735 non-null  float64
 19  T_out        19735 non-null  float64
 20  Press_mm_hg  19735 non-null  float64
 21  RH_out       19735 non-null  float64
 22  Windspeed    19735 non-null  float64
 23  Visibility   19735 non-null  float64
 24  Tdewpoint    19735 non-null  float64
 25  rv1          19735 non-null  float64
 26  rv2          19735 non-null  float64
dtypes: float64(26), int64(1)
memory usage: 4.1 MB

In [47]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression,Ridge,Lasso
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(energy), columns=energy.columns)
features_df = normalised_df[['T2']]
heating_target = normalised_df[['T6']]

In [48]:
#Now, we split our dataset into the training and testing dataset. Recall that we had earlier segmented the features and target variables.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_df, heating_target, test_size=0.30, random_state=42)

In [49]:
linear_model = LinearRegression()
#fit the model to the training dataset
linear_model.fit(x_train, y_train)
#obtain predictions
predicted_values = linear_model.predict(x_test)

In [50]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
print("The R2 score is:",r2_score)
print("The Rounded R2 Score is:",round(r2_score))

The R2 score is: 0.6427789637197382
The Rounded R2 Score is: 1.0

-------------------------------------------------------------------------------------------------------------------------------

## Q13)

In [51]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression,Ridge,Lasso
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(energy), columns=energy.columns)
features_df = normalised_df
heating_target = normalised_df['Appliances']

In [52]:
#Now, we split our dataset into the training and testing dataset. Recall that we had earlier segmented the features and target variables.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features_df, heating_target, test_size=0.30, random_state=42)

In [53]:
linear_model = LinearRegression()
#fit the model to the training dataset
linear_model.fit(x_train, y_train)
#obtain predictions
predicted_values = linear_model.predict(x_test)

In [54]:
#MAE
from sklearn.metrics import mean_absolute_error
import numpy as np
predicted_values = np.around(predicted_values,6)
mae = mean_absolute_error(y_test, predicted_values)
print("{:.2f}".format(float(mae)))

0.00

## Q14)

In [55]:
import numpy as np
rss = np.sum(np.square(y_test - predicted_values))
print("{:.2f}".format(float(rss)))

0.00

## Q15)

In [56]:
from sklearn.metrics import  mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
print("{:.3f}".format(float(rmse)))

0.000

## Q16)

In [57]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
print("The R2 score is:",r2_score)

The R2 score is: 0.9999999999922421

## Q17)

In [58]:
#comparing the effects of regularisation
def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
    model.fit(x_train,y_train)
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [59]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
model = LinearRegression()
lasso_reg = Lasso(alpha=0.001)
ridge_reg = Ridge(alpha=0.001)
linear_model_weights = get_weights_df(model, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')


final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

In [63]:
pd.options.display.float_format = '{:,.20f}'.format
final_weights

,Features,Linear_Model_Weight,Ridge_Weight,Lasso_weight
0,RH_2,-0.00000000000000015719,-0.00000417379632288627,-0.00000000000000000000
1,RH_out,-0.00000000000000008662,-0.00000070936207098539,-0.00000000000000000000
2,RH_3,-0.00000000000000004589,0.00000087801029525027,0.00000000000000000000
3,T3,-0.00000000000000003004,0.00000265675199980225,0.00000000000000000000
4,rv2,-0.00000000000000002629,0.00000000703960484427,-0.00000000000000000000
5,rv1,-0.00000000000000002629,0.00000000703915548007,-0.00000000000000000000
6,T9,-0.00000000000000001785,-0.00000173635107661134,0.00000000000000000000
7,Visibility,-0.00000000000000000988,0.00000011249601494817,0.00000000000000000000
8,T2,-0.00000000000000000161,-0.00000215815595661446,0.00000000000000000000
9,RH_7,0.00000000000000000757,-0.00000040787443671905,-0.00000000000000000000
10,RH_8,0.00000000000000002046,-0.00000144066687031465,-0.00000000000000000000
11,Tdewpoint,0.00000000000000002222,0.00000107549522664058,0.00000000000000000000
12,RH_1,0.00000000000000002268,0.00000505946674504144,0.00000000000000000000
13,T_out,0.00000000000000002954,-0.00000294062282321283,0.00000000000000000000
14,RH_6,0.00000000000000003125,0.00000034775575726061,-0.00000000000000000000
15,T4,0.00000000000000005517,0.00000026489555784320,0.00000000000000000000
16,RH_4,0.00000000000000005949,0.00000024116504375173,0.00000000000000000000
17,T6,0.00000000000000006167,0.00000216079786116238,0.00000000000000000000
18,T8,0.00000000000000010043,0.00000093238206147759,0.00000000000000000000
19,T7,0.00000000000000011194,0.00000009432687064362,0.00000000000000000000
20,T5,0.00000000000000011418,-0.00000014324131534793,0.00000000000000000000
21,T1,0.00000000000000012097,-0.00000003039495290100,0.00000000000000000000
22,RH_5,0.00000000000000012906,0.00000014632374275990,0.00000000000000000000
23,Press_mm_hg,0.00000000000000015478,0.00000006251720161280,-0.00000000000000000000
24,RH_9,0.00000000000000016330,-0.00000036388068859407,-0.00000000000000000000
25,Windspeed,0.00000000000000018098,0.00000026681333203425,0.00000000000000000000
26,Appliances,1.00000000000000066613,0.99999085836861401066,0.89199113510266925253

## Q18)

In [90]:
# Train model with default alpha=1
ridge = Ridge(alpha=0.4).fit(x_train, y_train)
ridge_pred = ridge.predict(x_test)

In [91]:
from sklearn.metrics import  mean_squared_error
ridge_pred = np.around(ridge_pred,6)
rmse = np.sqrt(mean_squared_error(y_test, ridge_pred))
print("{:.3f}".format(float(rmse)))

0.000

## Q19)

In [92]:
# Train model with default alpha=1
lasso = Lasso(alpha=0.001).fit(x_train, y_train)
lasso_pred = lasso.predict(x_test)

In [71]:
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

In [83]:
lasso_weights_df[lasso_weights_df['Lasso_weight']==0]

       Features  Lasso_weight
0            T7             0
1     Tdewpoint             0
2    Visibility             0
3     Windspeed             0
4        RH_out            -0
5   Press_mm_hg            -0
6         T_out             0
7          RH_9            -0
8            T9             0
9          RH_8            -0
10           T8             0
11         RH_7            -0
12          rv1            -0
13          rv2            -0
14           T6             0
15         RH_5             0
16           T5             0
17         RH_4             0
18           T4             0
19         RH_3             0
20           T3             0
21         RH_2            -0
22           T2             0
23         RH_1             0
24           T1             0
25         RH_6            -0

## Q20)

In [94]:
from sklearn.metrics import  mean_squared_error
lasso_pred = np.around(lasso_pred,6)
rmse = np.sqrt(mean_squared_error(y_test, lasso_pred))
print("{:.3f}".format(float(rmse)))

0.010